package com.linkedais.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * User Entity - Represents a user in our database
 * 
 * This class defines what information we store about each user.
 * Each instance of this class = one row in the "users" database table.
 */
@Entity  // This tells Spring this is a database table
@Table(name = "users")  // The table will be called "users" in the database
public class User {
    
    // Primary Key - unique ID for each user (auto-generated by database)
    @Id  // This is the primary key column
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Database automatically assigns IDs: 1, 2, 3, 4...
    private Long id;

    // Email column - must be unique (no two users can have same email) and not empty
    @Column(unique = true, nullable = false)
    private String email;

    // Password column - stores HASHED password (never store plain text passwords!)
    @Column(nullable = false)  // Cannot be empty
    private String password;

    // User's display name (optional - can be null)
    private String name;

    // roles
    @Column(nullable = false)
    private String role = "USER"; // visi vartotojai default bus useriai

    @Column(length = 500)
    private String bio;

    @Column(length = 200)
    private String university;

    @Column(name = "study_program", length = 200)
    private String studyProgram;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_skills", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "skill", length = 50)
    private List<String> skills = new ArrayList<>();

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
        name = "user_courses",
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "course_id")
    )
    private List<Course> courses = new ArrayList<>();

    @Column(name = "degree_progress")
    private Integer degreeProgress;

    @Column(name = "upcoming_schedule", length = 1000)
    private String upcomingSchedule;

    @Column(name = "academic_record_summary", length = 1000)
    private String academicRecordSummary;
    @ElementCollection
    @CollectionTable(name="user_completed_courses", joinColumns=@JoinColumn(name="user_id"))
    @Column(name="course_id")
    private List<Long> completedCourseIds = new ArrayList<>();


    // Timestamp when user registered
    @Column(name = "created_at")  // Column name in database will be "created_at"
    private LocalDateTime createdAt;

    /**
     * This method runs automatically BEFORE saving a new user to database
     * It sets the createdAt timestamp to current time
     */
    @PrePersist  // Run this before inserting into database
    protected void onCreate() {
        createdAt = LocalDateTime.now();  // Set to current date and time
    }

    // ==================== CONSTRUCTORS ====================
    
    /**
     * Default constructor (required by JPA/Hibernate)
     * Used when loading users from database
     */
    public User() {}

    /**
     * Constructor for creating a new user
     * 
     * @param email - User's email address
     * @param password - User's HASHED password (never pass plain text!)
     * @param name - User's display name
     */
    public User(String email, String password, String name) {
        this.email = email;
        this.password = password;
        this.name = name;
    }

    // ==================== GETTERS AND SETTERS ====================
    // These methods let other code read and update the private fields
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getUniversity() {
        return university;
    }

    public void setUniversity(String university) {
        this.university = university;
    }

    public String getStudyProgram() {
        return studyProgram;
    }

    public void setStudyProgram(String studyProgram) {
        this.studyProgram = studyProgram;
    }

    public List<String> getSkills() {
        return skills;
    }

    public void setSkills(List<String> skills) {
        this.skills = skills;
    }

    public List<Course> getCourses() {
        return courses;
    }

    public void setCourses(List<Course> courses) {
        this.courses = courses;
    }

    public Integer getDegreeProgress() {
        return degreeProgress;
    }

    public void setDegreeProgress(Integer degreeProgress) {
        this.degreeProgress = degreeProgress;
    }

    public String getUpcomingSchedule() {
        return upcomingSchedule;
    }

    public void setUpcomingSchedule(String upcomingSchedule) {
        this.upcomingSchedule = upcomingSchedule;
    }

    public String getAcademicRecordSummary() {
        return academicRecordSummary;
    }

    public void setAcademicRecordSummary(String academicRecordSummary) {
        this.academicRecordSummary = academicRecordSummary;
    }
    public List<Long> getCompletedCourseIds() { return completedCourseIds; }

    public void setCompletedCourseIds(List<Long> completedCourseIds) { this.completedCourseIds = completedCourseIds; }

    public void setRole(String role) {
        this.role = role;
    }

    public String getRole(){
        return role;
    }
}
