package com.linkedais.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * User Entity - Represents a user in our database
 * 
 * This class defines what information we store about each user.
 * Each instance of this class = one row in the "users" database table.
 */
@Entity  // This tells Spring this is a database table
@Table(name = "users")  // The table will be called "users" in the database
public class User {
    
    // Primary Key - unique ID for each user (auto-generated by database)
    @Id  // This is the primary key column
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Database automatically assigns IDs: 1, 2, 3, 4...
    private Long id;

    // Email column - must be unique (no two users can have same email) and not empty
    @Column(unique = true, nullable = false)
    private String email;

    // Password column - stores HASHED password (never store plain text passwords!)
    @Column(nullable = false)  // Cannot be empty
    private String password;

    // User's display name (optional - can be null)
    private String name;

    // Timestamp when user registered
    @Column(name = "created_at")  // Column name in database will be "created_at"
    private LocalDateTime createdAt;

    /**
     * This method runs automatically BEFORE saving a new user to database
     * It sets the createdAt timestamp to current time
     */
    @PrePersist  // Run this before inserting into database
    protected void onCreate() {
        createdAt = LocalDateTime.now();  // Set to current date and time
    }

    // ==================== CONSTRUCTORS ====================
    
    /**
     * Default constructor (required by JPA/Hibernate)
     * Used when loading users from database
     */
    public User() {}

    /**
     * Constructor for creating a new user
     * 
     * @param email - User's email address
     * @param password - User's HASHED password (never pass plain text!)
     * @param name - User's display name
     */
    public User(String email, String password, String name) {
        this.email = email;
        this.password = password;
        this.name = name;
    }

    // ==================== GETTERS AND SETTERS ====================
    // These methods let other code read and update the private fields
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
